In [1]:
# We are going to start TensorFlow Basics here

In [3]:
import tensorflow as tf

In [5]:
print(tf.__version__)

2.19.0


In [6]:
#Creatint Tensor with constant
#function here that we can use to create
scalar=tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [7]:
scalar.ndim

0

In [8]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
vector.ndim

1

In [11]:
matrix=tf.constant([[5,9],[9,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  9],
       [ 9, 11]], dtype=int32)>

In [12]:
matrix.ndim

2

In [37]:
second_matrix=tf.constant([[5,7],[3,8],
                           [3,9],
                           [4,2],
                           [8,6]])

In [38]:
second_matrix

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 7],
       [3, 8],
       [3, 9],
       [4, 2],
       [8, 6]], dtype=int32)>

In [39]:
second_matrix.ndim

2

In [40]:
third_matrix=tf.constant(
    [
   [[1,2,3],
   [2,4,5]],
   [[7,9,3],
   [10,4,5]],
   [[11,2,3],
   [2,4,15]],
          ] )
third_matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  4,  5]],

       [[ 7,  9,  3],
        [10,  4,  5]],

       [[11,  2,  3],
        [ 2,  4, 15]]], dtype=int32)>

In [41]:
second_matrix=tf.constant([[5,6,7,3],[3,45,8,25],
                           [3,11,9,23],
                           [4,34,2,34],
                           [8,4,6,23]],dtype=tf.float16)
print(second_matrix)


tf.Tensor(
[[ 5.  6.  7.  3.]
 [ 3. 45.  8. 25.]
 [ 3. 11.  9. 23.]
 [ 4. 34.  2. 34.]
 [ 8.  4.  6. 23.]], shape=(5, 4), dtype=float16)


In [42]:
# single number that means scalar
scalar=tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [43]:
# a number with a direction
vector=tf.constant([10,10,20,30])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10, 20, 30], dtype=int32)>

In [44]:
# a 2-D array of number
matrix=tf.constant([[10,20],[30,40]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [45]:
#Tensor : an n-dimensional array of numbers (n=0,n=1,n=2......)
tensor=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [46]:
# Find the shape, rank and size of the tensors
print("Scalar Information")
print("Shape:",scalar.shape)
print("Dimension:",scalar.ndim)
print("Rank:",tf.size(scalar).numpy())
print("Size:",tf.rank(scalar))

Scalar Information
Shape: ()
Dimension: 0
Rank: 1
Size: tf.Tensor(0, shape=(), dtype=int32)


In [47]:
print("Vector Information")
print("Shape:",vector.shape)
print("Dimension:",vector.ndim)
print("Rank:",tf.size(vector).numpy())
print("Size:",tf.rank(vector))

Vector Information
Shape: (4,)
Dimension: 1
Rank: 4
Size: tf.Tensor(1, shape=(), dtype=int32)


In [48]:
print("Matrix Information")
print("Shape:",matrix.shape)
print("Dimension:",matrix.ndim)
print("Rank:",tf.size(matrix).numpy())
print("Size:",tf.rank(matrix))

Matrix Information
Shape: (2, 2)
Dimension: 2
Rank: 4
Size: tf.Tensor(2, shape=(), dtype=int32)


In [49]:
print("Tensor Information")
print("Shape:",tensor.shape)
print("Dimension:",tensor.ndim)
print("Rank:",tf.size(tensor).numpy())
print("Size:",tf.rank(tensor))

Tensor Information
Shape: (2, 2, 2)
Dimension: 3
Rank: 8
Size: tf.Tensor(3, shape=(), dtype=int32)


In [64]:
# Creating Tensor using Variable
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [65]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [66]:
changeable_tensor[1].assign(15)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 15], dtype=int32)>

In [67]:
changeable_tensor[1].assign(75)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 75], dtype=int32)>

In [68]:
#unchangeable_tensor[0].assign(12)
#unchangeable_tensor
#this will be an error because you cant change constant tensor. They are Immutable i.e. unchangeable

In [60]:
#Random Tensors
random_tensor=tf.random.Generator.from_seed(42)
random_tensor=random_tensor.normal(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [69]:
random_tensor_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
random_tensor_2

<tf.Tensor: shape=(300, 150), dtype=float32, numpy=
array([[0.25092006, 0.5959755 , 0.03434134, ..., 0.7887008 , 0.3397286 ,
        0.39368236],
       [0.29503036, 0.53458226, 0.10447419, ..., 0.7821249 , 0.44814956,
        0.29295075],
       [0.95041454, 0.09903157, 0.02042377, ..., 0.23047268, 0.68564963,
        0.222332  ],
       ...,
       [0.40154123, 0.26368296, 0.9753622 , ..., 0.25052583, 0.02921867,
        0.9787396 ],
       [0.0914607 , 0.7048178 , 0.08106136, ..., 0.6631715 , 0.5785239 ,
        0.03683555],
       [0.95850277, 0.03920305, 0.9513998 , ..., 0.60000575, 0.4819746 ,
        0.37903798]], dtype=float32)>

In [72]:
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.int16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [73]:
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.float32)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [74]:
 #Tensor for all ones
 tensor_ones=tf.ones(shape=(3,4),dtype=tf.dtypes.int16)
 tensor_ones

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)>

In [91]:
import numpy as np
numpy_Array=np.arange(1,25,dtype=np.int16)
numpy_Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [92]:
tensor_numpy=tf.constant(numpy_Array,shape=(2,3,4))
tensor_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [94]:
print("Tensor Information")
print("Shape:",tensor_numpy.shape)
print("Dimension:",tensor_numpy.ndim)
print("Rank:",tf.size(tensor_numpy).numpy())
print("Size:",tf.rank(tensor_numpy))
print("DataType of elements:",tensor_numpy.dtype)
print("Element along axis 0:",tensor_numpy.shape[0])
print("Element along axis 1:",tensor_numpy.shape[1])
print("Element along axis 2:",tensor_numpy.shape[2])
print("Total number of element:\t", tf.size(tensor_numpy).numpy())

Tensor Information
Shape: (2, 3, 4)
Dimension: 3
Rank: 24
Size: tf.Tensor(3, shape=(), dtype=int32)
DataType of elements: <dtype: 'int16'>
Element along axis 0: 2
Element along axis 1: 3
Element along axis 2: 4
Total number of element:	 24


In [95]:
#working with items of each dimension
tensor_numpy[:3,:3,:3]

<tf.Tensor: shape=(2, 3, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]], dtype=int16)>

In [96]:
#first elements of each dimension
tensor_numpy[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1), dtype=int16, numpy=array([[[1]]], dtype=int16)>

In [97]:
#first two elements of each dimension
tensor_numpy[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int16)>

** Arthmetic Operations with Tensors **


*   Add
*   Sub
*   Multi
*   Div





In [75]:
tensor_one=tf.constant(([11,9],[2,5]))
tensor_one

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 2,  5]], dtype=int32)>

In [82]:
#tensor_one+15
tf.add(tensor_one,15)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [98]:
#tensor_one-5
tf.subtract(tensor_one,5)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [99]:
#tensor_one*2
tf.multiply(tensor_one,2)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [83]:
#tensor_one/2
tf.divide(tensor_one,2)

<tf.Tensor: shape=(), dtype=float64, numpy=7.5>

In [101]:
tf.square(tensor_one)

<tf.Tensor: shape=(), dtype=int32, numpy=225>

In [87]:
second_matrix=tf.constant([[8,16],[64,8.25],
                           [625,9.23],
                           [125,2.34],
                           [169,144]],dtype=tf.float32)
print(second_matrix)

tf.Tensor(
[[  8.    16.  ]
 [ 64.     8.25]
 [625.     9.23]
 [125.     2.34]
 [169.   144.  ]], shape=(5, 2), dtype=float32)


In [89]:
tf.sqrt(second_matrix)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 2.828427 ,  4.       ],
       [ 8.       ,  2.8722813],
       [25.       ,  3.0380914],
       [11.18034  ,  1.5297059],
       [13.       , 12.       ]], dtype=float32)>

Exercise Create two tensors with random values between 0 and 1 , shape is [6,300]
**Find out the following details: **
Number of elements
Size,
Rank,
Shape


In [103]:
import tensorflow as tf

# Create two tensors with random values between 0 and 1, shape [6, 300]
tensor_a = tf.random.uniform(shape=[6, 300], minval=0, maxval=1)
tensor_b = tf.random.uniform(shape=[6, 300], minval=0, maxval=1)

# Display the tensors
print("Tensor A:\n", tensor_a)
print("\nTensor B:\n", tensor_b)

# Find details for Tensor A
print("\n--- Details for Tensor A ---")
print("Shape:", tensor_a.shape)
print("Number of elements:", tf.size(tensor_a).numpy())
print("Rank:", tf.rank(tensor_a).numpy())
print("Size in bytes:", tensor_a.numpy().nbytes)

# Find details for Tensor B
print("\n--- Details for Tensor B ---")
print("Shape:", tensor_b.shape)
print("Number of elements:", tf.size(tensor_b).numpy())
print("Rank:", tf.rank(tensor_b).numpy())
print("Size in bytes:", tensor_b.numpy().nbytes)


Tensor A:
 tf.Tensor(
[[0.98743546 0.23427796 0.74780023 ... 0.7268411  0.07491183 0.32668197]
 [0.41621935 0.87397873 0.9211718  ... 0.61644197 0.7691647  0.1703918 ]
 [0.7792754  0.18601894 0.50279546 ... 0.84848166 0.6007118  0.5589969 ]
 [0.7694919  0.6124102  0.6855781  ... 0.9608859  0.05455315 0.43248618]
 [0.83459866 0.22186637 0.7943877  ... 0.37017798 0.0018456  0.0813812 ]
 [0.80548406 0.77427864 0.55422616 ... 0.7744298  0.26224315 0.03373468]], shape=(6, 300), dtype=float32)

Tensor B:
 tf.Tensor(
[[0.4460963  0.68337727 0.17450714 ... 0.97159135 0.47961366 0.12057912]
 [0.08591235 0.6585349  0.4810971  ... 0.0864836  0.05202556 0.10988355]
 [0.0420599  0.95953894 0.5051476  ... 0.75765455 0.48788345 0.9175731 ]
 [0.27335143 0.51611745 0.38761318 ... 0.45126426 0.9898945  0.8290292 ]
 [0.22579181 0.56967556 0.0996058  ... 0.5950624  0.93660665 0.5760124 ]
 [0.41182232 0.49907565 0.7752801  ... 0.55147624 0.5701053  0.6577476 ]], shape=(6, 300), dtype=float32)

--- Details 