**Mini Project Airline Tweet Sentiment Classifier using Natural Language Processing**

Notes: Use sample dataset: https://github.com/salman1256/aimltraining/blob/main/Day-30/airline_tweets_sample.csv



---


Steps:
1. libraries
2. Load and explore dataset
3. Convert text to numerical vectors (TF-IDF)
4. Split into train and test sets
5. Train a Logistic Regression model
6. Evaluate accuracy and classification report
7. Predict sentiment for new example tweets

In [220]:
# Step 1 a: Import Required Libraries
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import re
import nltk
from nltk.corpus import stopwords
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
import string
from sklearn.preprocessing import LabelEncoder

In [221]:
# Step 1 b: Download nltk required thing like stopwords
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [222]:
# Step 2 a: Load DataSet
df = pd.read_csv('/content/airline_tweets_sample.csv')
df.head()

text sentiment
0  @United flight was delayed for 3 hours, worst ...  negative
1  Loved the service on @Delta, crew was super fr...  positive
2  @AmericanAir lost my luggage again, so disappo...  negative
3  Smooth boarding and on-time arrival. Great job...  positive
4  The seats were uncomfortable but staff was polite   neutral

In [223]:
# Step 3:
# Text Cleaning and Preprocessing
# For each tweet do:
# a. Convert to lowercase
# b. Remove URLs
# c. Remove special characters and numbers
# d. Remove stopwords (common words like *the, is, and* etc.)
# e. Apply **stemming** (reduce words to their root form)

def clean_text(text):
  text=text.lower()
  text=re.sub(r'http\S+',' ',text)
  text=re.sub(r'www\S+',' ',text)
  text = re.sub(r'[^a-zA-Z]', ' ', text)
  text = re.sub(r'\s+',' ', text).strip()

  stemmer = PorterStemmer()
  stop_words = set(stopwords.words('english')) - {'no', 'not', 'never'}
  text = ' '.join([stemmer.stem(word) for word in text.split() if word not in stop_words])
  return text

In [224]:
df['cleaned_text'] = df['text'].apply(clean_text)
df

text sentiment  \
0   @United flight was delayed for 3 hours, worst ...  negative   
1   Loved the service on @Delta, crew was super fr...  positive   
2   @AmericanAir lost my luggage again, so disappo...  negative   
3   Smooth boarding and on-time arrival. Great job...  positive   
4   The seats were uncomfortable but staff was polite   neutral   
5   @JetBlue flight attendants were rude, not flyi...  negative   
6   Got a free upgrade to business class, thank yo...  positive   
7          Average flight, nothing special to mention   neutral   
8   @DeltaAirLines provided excellent support with...  positive   
9         The in-flight entertainment was not working  negative   
10      Snacks were good but the legroom was terrible  negative   
11             @SouthwestAir always makes flying fun!  positive   
12                Check-in process was quick and easy  positive   
13    Customer service kept me on hold for 40 minutes  negative   
14  Flight was okay, staff were fine, nothing to c...   neutral   
15           Super smooth landing, kudos to the pilot  positive   
16      I missed my connection because of their delay  negative   
17    @AmericanAir helped me rebook my flight quickly  positive   
18                    Cabin was clean and comfortable  positive   
19     They refused to change my seat, very unhelpful  negative   
20     Just an ordinary flight, everything was normal   neutral   
21               Loved the new in-flight menu options  positive   
22                         Baggage claim took forever  negative   
23                   Polite crew but very noisy cabin   neutral   
24  @UnitedAirlines app kept crashing during check-in  negative   
25        Had extra legroom and free snacks, amazing!  positive   
26              Boarding was chaotic and disorganized  negative   
27          Comfortable seats and great WiFi on board  positive   
28             Staff did their best despite the delay   neutral   
29                  Worst airline experience in years  negative   

                                      cleaned_text  
0         unit flight delay hour worst experi ever  
1            love servic delta crew super friendli  
2               americanair lost luggag disappoint  
3   smooth board time arriv great job southwestair  
4                       seat uncomfort staff polit  
5                jetblu flight attend rude not fli  
6            got free upgrad busi class thank unit  
7               averag flight noth special mention  
8            deltaairlin provid excel support book  
9                        flight entertain not work  
10                      snack good legroom terribl  
11                 southwestair alway make fli fun  
12                        check process quick easi  
13                   custom servic kept hold minut  
14            flight okay staff fine noth complain  
15                    super smooth land kudo pilot  
16                              miss connect delay  
17          americanair help rebook flight quickli  
18                             cabin clean comfort  
19                         refus chang seat unhelp  
20                  ordinari flight everyth normal  
21                     love new flight menu option  
22                         baggag claim took forev  
23                          polit crew noisi cabin  
24               unitedairlin app kept crash check  
25                   extra legroom free snack amaz  
26                          board chaotic disorgan  
27                   comfort seat great wifi board  
28                         staff best despit delay  
29                        worst airlin experi year

In [225]:
# Step 4:
# a) Convert text to numerical vectors (TF-IDF)
# b) check X,y and shape len
le=LabelEncoder()
df['sentiment']=le.fit_transform(df['sentiment'])
X=df['cleaned_text']
y=df['sentiment']
X
y

0     0
1     2
2     0
3     2
4     1
5     0
6     2
7     1
8     2
9     0
10    0
11    2
12    2
13    0
14    1
15    2
16    0
17    2
18    2
19    0
20    1
21    2
22    0
23    1
24    0
25    2
26    0
27    2
28    1
29    0
Name: sentiment, dtype: int64

In [226]:
X.shape, y.shape, len(X)

((30,), (30,), 30)

In [227]:
# Step 5: Split into train and test sets
# 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [228]:
tfidf = TfidfVectorizer(max_features=5000, sublinear_tf=True)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [229]:
# Step 6: Train a Logistic Regression model
# a: Create Logistic Model
# b: Train Logistic Model
model=LogisticRegression()
model.fit(X_train_tfidf,y_train)

LogisticRegression()

In [230]:
# Step 7:
# Evaluate accuracy and classification report
# a. predict Model
# b. Precision, reacll, F1-Score for each sentiments
y_pred=model.predict(X_test_tfidf)
print('Accuracy',accuracy_score(y_test,y_pred))
print('Confusion Matrix\n',confusion_matrix(y_test,y_pred))
print("\n Classification Report:\n", classification_report(y_test, y_pred))

Accuracy 0.3333333333333333
Confusion Matrix
 [[1 0 0]
 [0 0 1]
 [3 0 1]]

 Classification Report:
               precision    recall  f1-score   support

           0       0.25      1.00      0.40         1
           1       0.00      0.00      0.00         1
           2       0.50      0.25      0.33         4

    accuracy                           0.33         6
   macro avg       0.25      0.42      0.24         6
weighted avg       0.38      0.33      0.29         6



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [231]:
# Step 8: Predict sentiment for new example tweets
new_tweet = [
    "The flight was very comfortable and the staff were really friendly and helpful!",
    "My flight got delayed and the airline didn’t provide any updates!",
    "The flight was fine, nothing went wrong but nothing was particularly impressive either."
]
new_clean_tweet = [clean_text(tweet) for tweet in new_tweet]
new_clean_tweet_vec = tfidf.transform(new_clean_tweet)
predictions = model.predict(new_clean_tweet_vec)

sentiment_map = {0: "Negative", 1: "Neutral", 2: "Positive"}

print('\nPredictions for new Tweets are:')
for msg, prediction in zip(new_tweet, predictions):
    print(f'{msg} --> {sentiment_map[prediction]}')


Predictions for new Tweets are:
The flight was very comfortable and the staff were really friendly and helpful! --> Positive
My flight got delayed and the airline didn’t provide any updates! --> Negative
The flight was fine, nothing went wrong but nothing was particularly impressive either. --> Neutral
