# Numpy Introduction and Usage
## We will use numpy in this jupyter noteook

# One Dimensional Array (1-D)

In [1]:
import numpy as np

In [71]:
array1=np.array([10,20,30,40,50,80])

In [72]:
print(array1)

[10 20 30 40 50 80]


# Two Dimensional Array (2-D)

In [73]:
array_two=np.array([[10,20,30],[40,50,70]])

# Three Dimensional Array (3-D Array)

In [74]:
array_three=np.array([[[10,20,30],[40,50,70]],[[10,20,30],[40,50,70]]])

In [75]:
print(array_three)

[[[10 20 30]
  [40 50 70]]

 [[10 20 30]
  [40 50 70]]]


# Find out Dimension of NumPy array

In [76]:
print('First Array Dimension: \t',array1.ndim)

First Array Dimension: 	 1


In [77]:
print('Second Array Dimension: \t',array_two.ndim)

Second Array Dimension: 	 2


In [78]:
print('Third Array Dimension: \t',array_three.ndim)

Third Array Dimension: 	 3


# Write an array of 5 students marks using Numpy
    ## Marks are: 50,70,75,99.89

In [79]:
marks = np.array([50, 70, 75, 99, 89])

In [80]:
print('Students marks:')
print(marks)

Students marks:
[50 70 75 99 89]


# Write an array: to take marks of 5 students in 3 subjects using Numpy
## Math, English, Chemistry
## [50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]]

In [81]:
marks_subject=np.array([[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]])
print('2 D array Examples')
print(marks_subject)

2 D array Examples
[[50 45 49]
 [40 42 45]
 [35 40 46]
 [39 40 45]
 [48 40 40]]


# Write an array: to take Marks of 4 students in 3 subjects for two semester using Numpy
    ## Students Name are: 'Amit','Sha','Xi','Arif'
    ## Math, English, Chemistry
    ## Two Semester: Sem1, Sem2
    ## 4*3*2
    ## ([[[85,88],[78,82][90,95]],[[76,70],[40,45][90,90]],[[80,86],[78,82][90,95]],[[85,88],[78,82][70,90]]])

In [82]:
marks_subject_sem=np.array([
    [[85,88],[78,82],[90,95]],
    [[76,70],[40,45],[90,90]],
    [[80,86],[78,82],[90,95]],
    [[85,88],[78,82],[70,90]]
])

In [83]:
print (marks_subject_sem)

[[[85 88]
  [78 82]
  [90 95]]

 [[76 70]
  [40 45]
  [90 90]]

 [[80 86]
  [78 82]
  [90 95]]

 [[85 88]
  [78 82]
  [70 90]]]


# Write an array: to take wheater of 2 cities in 3 days for three times in a day morning, noon, evening
    ## Cities Name are: 'Kuala Lumpur, 'Delhi'
    ## Saturday, Sunday, Monday
    ## Three Time Slot: Morning Noon, Evening
    ### this is degree celsius:
    ## ([[[28, 32, 29],[27, 33, 30],[26, 31, 28]],  
    [[22, 30, 25],[24, 32, 26],[23, 31, 27]]])
# Create one 3 D Array for this using NumPy and print it

In [84]:
wheater_2_cities=np.array([
    [[28, 32, 29],[27, 33, 30],[26, 31, 28]],
    [[22, 30, 25],[24, 32, 26],[23, 31, 27]]
])

In [85]:
print (wheater_2_cities)

[[[28 32 29]
  [27 33 30]
  [26 31 28]]

 [[22 30 25]
  [24 32 26]
  [23 31 27]]]


In [86]:
print("\nShape of array:", wheater_2_cities.shape)


Shape of array: (2, 3, 3)


# Basic Information
    ## shape: rows and columns
    ## size: number of elements
    ## Dimension: return dimension 1,2,3...
    ## Data Type: return stored data values type

In [87]:
print(array1)

[10 20 30 40 50 80]


In [88]:
print("Shape of array1:",array1.shape)

Shape of array1: (6,)


In [89]:
print("size of array1:",array1.size)

size of array1: 6


In [90]:
print ('Dimension: ',array1.ndim)

Dimension:  1


In [91]:
print('Data Type: ',array1.dtype)

Data Type:  int64


In [92]:
students=np.array(['Ali Munaf Bin Kabir','Shi','Xi','Meena','Ziva'])

In [93]:
print(students)

['Ali Munaf Bin Kabir' 'Shi' 'Xi' 'Meena' 'Ziva']


In [94]:
print('Shape of Array:',students.shape)

Shape of Array: (5,)


In [96]:
print('Number of students',students.size)

Number of students 5


In [97]:
print('Data Type:', students.dtype)

Data Type: <U19


# Mathematical Operation

In [98]:
print(array1)

[10 20 30 40 50 80]


In [99]:
total=np.sum(array1)

In [100]:
print(total)

230


In [101]:
print('Mean:',np.mean(array1))

Mean: 38.333333333333336


In [102]:
print('Min:',np.min(array1))

Min: 10


In [103]:
print('Max:',np.max(array1))

Max: 80


In [104]:
print('Index of Min:',np.argmin(array1))

Index of Min: 0


In [106]:
print('Index of Max:',np.argmax(array1))

Index of Max: 5


In [107]:
our_arr=np.array([100,200,300,7000,400,500,300,1900,600])

In [108]:
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


# Searching and Sorting Example in 1 D Array

In [109]:
sorted_arr=np.sort(our_arr)
print('*** Sorted Array')
print(sorted_arr)

*** Sorted Array
[ 100  200  300  300  400  500  600 1900 7000]


In [111]:
print('any item greater than 500 ?: ',np.any(sorted_arr>500))

any item greater than 500 ?:  True


In [112]:
print('any item greater than 99 ?: ',np.any(sorted_arr>99))

any item greater than 99 ?:  True


In [113]:
print('Where values >500',np.where(sorted_arr>500))

Where values >500 (array([6, 7, 8]),)


In [114]:
print('All number greater than 500')
for num in np.where(sorted_arr>500):
    print(num)

All number greater than 500
[6 7 8]


In [115]:
print('All Number greater than 500')
for num in sorted_arr>500:
    print(num)

All Number greater than 500
False
False
False
False
False
False
True
True
True


In [116]:
selected_values=sorted_arr[sorted_arr>500]

In [117]:
print(selected_values)

[ 600 1900 7000]


In [118]:
for num in selected_values:
    print(num)

600
1900
7000


In [119]:
print(' ',sorted_arr[sorted_arr>500])

  [ 600 1900 7000]


# Slicing 1 D Array
    1. To take elements from starting index to end index
    2. e.g. [start:end]

In [128]:
print(sorted_arr)

[ 100  200  300  300  400  500  600 1900 7000]


In [130]:
slice_sorted_arr=sorted_arr[1:5]
print(slice_sorted_arr)

[200 300 300 400]


# starting from an index and going till last

In [131]:
print(sorted_arr[3:])

[ 300  400  500  600 1900 7000]


In [132]:
print(sorted_arr[:4])

[100 200 300 300]


In [133]:
print(sorted_arr[:5])

[100 200 300 300 400]


# step
    ## [start:end:step]
    ## step: every step element

In [134]:
our_slice=sorted_arr[1:6:2]
print(our_slice)

[200 300 500]


In [136]:
print('Original Array')
print(sorted_arr)
print('Every Third Element')
every_third_element=sorted_arr[::3]
print(every_third_element)

Original Array
[ 100  200  300  300  400  500  600 1900 7000]
Every Third Element
[100 300 600]


# Slice Reverse

In [137]:
print('Original Array')
print(sorted_arr)
print('Revers Array:')
print(sorted_arr[::-1])

Original Array
[ 100  200  300  300  400  500  600 1900 7000]
Revers Array:
[7000 1900  600  500  400  300  300  200  100]


In [138]:
print('Last five elements')
print(sorted_arr[-5:])

Last five elements
[ 400  500  600 1900 7000]


In [139]:
print('Slicing Done')

Slicing Done
